// pages/login.tsx
import Head from 'next/head';
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react';
import CustomSignInForm from '@/components/CustomSignInForm';
import Layout from './components/Layout'; // Import the original Layout component
import UserLayout from './components/UserLayout'; // Import the UserLayout component

export default function LoginPage() {
    const session = useSession();
    const supabase = useSupabaseClient();

    return (
        <>
            <Head>
                <title>SSTA Reminders & Tasks</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {session ? (
                <UserLayout>
                    <div className="w-full flex justify-center items-center p-4">
                        <div className="w-full sm:w-2/3 lg:w-3/4">
                            Welcome
                        </div>
                    </div>
                </UserLayout>
            ) : (
                <Layout>
                    <div className="w-full h-full bg-200">
                        <div className="min-w-full min-h-screen flex items-center justify-center">
                            <div className="w-full h-full flex justify-center items-center p-4">
                                <div className="w-full h-full sm:h-auto sm:w-2/5 max-w-sm p-5 bg-white shadow flex flex-col text-base">
                                    <span className="font-sans text-4xl text-center pb-2 mb-1 border-b mx-4 align-center">
                                        Lead Aggregator
                                    </span>
                                    <div className="mt-4">
                                        <CustomSignInForm />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </Layout>
            )}
        </>
    );
}